version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aiRead?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      JHIPSTER_CACHE_REDIS_SERVER: redis://redis:6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: docker.1ms.run/mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aiRead
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: docker.1ms.run/redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  mysql-data:
