package com.shanzha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChapterPackageItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageItemAllPropertiesEquals(ChapterPackageItem expected, ChapterPackageItem actual) {
        assertChapterPackageItemAutoGeneratedPropertiesEquals(expected, actual);
        assertChapterPackageItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageItemAllUpdatablePropertiesEquals(ChapterPackageItem expected, ChapterPackageItem actual) {
        assertChapterPackageItemUpdatableFieldsEquals(expected, actual);
        assertChapterPackageItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageItemAutoGeneratedPropertiesEquals(ChapterPackageItem expected, ChapterPackageItem actual) {
        assertThat(actual)
            .as("Verify ChapterPackageItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageItemUpdatableFieldsEquals(ChapterPackageItem expected, ChapterPackageItem actual) {
        assertThat(actual)
            .as("Verify ChapterPackageItem relevant properties")
            .satisfies(a -> assertThat(a.getPackageId()).as("check packageId").isEqualTo(expected.getPackageId()))
            .satisfies(a -> assertThat(a.getChapterId()).as("check chapterId").isEqualTo(expected.getChapterId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageItemUpdatableRelationshipsEquals(ChapterPackageItem expected, ChapterPackageItem actual) {
        // empty method
    }
}
