package com.shanzha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChapterPackageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageAllPropertiesEquals(ChapterPackage expected, ChapterPackage actual) {
        assertChapterPackageAutoGeneratedPropertiesEquals(expected, actual);
        assertChapterPackageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageAllUpdatablePropertiesEquals(ChapterPackage expected, ChapterPackage actual) {
        assertChapterPackageUpdatableFieldsEquals(expected, actual);
        assertChapterPackageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageAutoGeneratedPropertiesEquals(ChapterPackage expected, ChapterPackage actual) {
        assertThat(actual)
            .as("Verify ChapterPackage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageUpdatableFieldsEquals(ChapterPackage expected, ChapterPackage actual) {
        assertThat(actual)
            .as("Verify ChapterPackage relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterPackageUpdatableRelationshipsEquals(ChapterPackage expected, ChapterPackage actual) {
        // empty method
    }
}
